"""add series prefix

Revision ID: 295e5a33f801
Revises: 5653f0c8b683
Create Date: 2021-01-08 10:32:28.337951

"""

# revision identifiers, used by Alembic.
revision = '295e5a33f801'
down_revision = '5653f0c8b683'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('series_prefix', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('series', sa.Column('prefix', sa.String(length=16), nullable=False, server_default=''))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'prefix')
    op.drop_column('invoices', 'series_prefix')
    ### end Alembic commands ###
