"""added copy of customer fields to invoice

Revision ID: 76cfb65376ff
Revises: 4b75ad4ab96f
Create Date: 2016-04-25 13:40:50.053245

"""

# revision identifiers, used by Alembic.
revision = '76cfb65376ff'
down_revision = '4b75ad4ab96f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_contact_person', sa.String(length=127), nullable=True))
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=127), nullable=True))
    op.add_column('invoices', sa.Column('customer_invoicing_address', sa.Text(), nullable=False))
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=255), nullable=False))
    op.add_column('invoices', sa.Column('customer_shipping_address', sa.Text(), nullable=False))
    op.add_column('invoices', sa.Column('customer_tax_id', sa.String(length=63), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'customer_tax_id')
    op.drop_column('invoices', 'customer_shipping_address')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'customer_invoicing_address')
    op.drop_column('invoices', 'customer_email')
    op.drop_column('invoices', 'customer_contact_person')
    ### end Alembic commands ###
