"""added user and next invoice to series

Revision ID: 77a9fbbe4cd9
Revises: 7f3bd174f659
Create Date: 2021-01-07 23:31:43.287702

"""

# revision identifiers, used by Alembic.
revision = '77a9fbbe4cd9'
down_revision = '7f3bd174f659'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('next_invoice_num', sa.Integer(), nullable=False))
    op.add_column('series', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'series', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_column('series', 'user_id')
    op.drop_column('series', 'next_invoice_num')
    ### end Alembic commands ###
