"""added series model

Revision ID: 7f3bd174f659
Revises: df31ab078bb4
Create Date: 2021-01-07 23:17:24.010789

"""

# revision identifiers, used by Alembic.
revision = '7f3bd174f659'
down_revision = 'df31ab078bb4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    series_table = op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series')
    ### end Alembic commands ###
