"""added invoice model

Revision ID: a15fe29fe566
Revises: bdb82b2b0eb0
Create Date: 2016-04-14 20:44:53.860856

"""

# revision identifiers, used by Alembic.
revision = 'a15fe29fe566'
down_revision = 'bdb82b2b0eb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ref_num', sa.Integer(), nullable=False),
    sa.Column('issued_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    ### end Alembic commands ###
