"""added customer model

Revision ID: c4a9e4ab3bce
Revises: a15fe29fe566
Create Date: 2016-04-17 19:01:58.191577

"""

# revision identifiers, used by Alembic.
revision = 'c4a9e4ab3bce'
down_revision = 'a15fe29fe566'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=63), nullable=True),
    sa.Column('contact_person', sa.String(length=127), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('invoicing_address', sa.Text(), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tax_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    ### end Alembic commands ###
